import { AuthContextProvider } from "./_utils/auth-context"; // Adjust the path as per your project structure
import localFont from "next/font/local";

import "./globals.css";

const geistSans = localFont({
  src: "/fonts/GeistVF.woff", // Ensure this path is correct
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "/fonts/GeistMonoVF.woff", // Ensure this path is correct
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthContextProvider>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
